version: "3.9"

services:
  basic-app:
    build: 
      context: ./backend
    container_name: basic-app
    volumes:
      - ./backend:/usr/src/app/backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - FROM_DOCKER=1
      - CELERY_BROKER=redis://basic-app-redis:6379/0
      - CELERY_BACKEND=redis://basic-app-redis:6379/0
    depends_on:
      - basic-app-db
      - basic-app-redis
  
  basic-app-frontend:
    build:
      context: ./frontend/basic-app-frontend
    ports:
      - "3000:3000"
    environment: 
      - FROM_DOCKER=1
    volumes:
      - next_build:/usr/src/app/frontend/.next
  
  nginx:
    image: nginx:latest
    # command: bash -c "sudo chown -R www-data:www-data /var/www/.next ; sudo chmod 755 /var/www/.next ; sudo chmod 644 /var/www/.next/*"
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - next_build:/var/www/.next
    depends_on:
      - basic-app
      - basic-app-frontend

  basic-app-celery:
    build: 
      context: ./backend
    command: celery -A core worker -l INFO
    volumes:
      - ./backend:/usr/src/app/backend
    environment:
      - DEBUG=1
      - CELERY_BROKER=redis://basic-app-redis:6379/0
      - CELERY_BACKEND=redis://basic-app-redis:6379/0
    depends_on:
      - basic-app
      - basic-app-db
      - basic-app-redis

  basic-app-db:
    image: postgres
    container_name: basic-app-db
    environment:
      - POSTGRES_DB=basic_app_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - basic-app-db-data:/var/lib/postgresql/data

  basic-app-redis:
    image: redis

volumes:
  basic-app-db-data:
  next_build:
